# Generated by Django 5.2.5 on 2025-09-28 06:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('time_spent_sec', models.FloatField(default=0.0)),
                ('steps_planned', models.IntegerField(default=6)),
                ('steps_taken', models.IntegerField(default=0)),
                ('backtracks', models.IntegerField(default=0)),
                ('error_counts', models.IntegerField(default=0)),
                ('extra_clicks', models.IntegerField(default=0)),
                ('effectiveness', models.FloatField(default=0.0)),
                ('efficiency', models.FloatField(default=0.0)),
                ('satisfaction', models.FloatField(default=0.0)),
                ('usability_index', models.FloatField(default=0.0)),
                ('completion_status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failure', 'Failure')], default='failure', max_length=10)),
                ('fields_completed', models.IntegerField(default=0)),
                ('fields_required', models.IntegerField(default=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('failure', 'Failure')], max_length=10)),
                ('success_best_area', models.TextField(blank=True, help_text='What area of the form worked best for successful users', null=True)),
                ('success_notes', models.TextField(blank=True, help_text='Additional notes about successful completion', null=True)),
                ('failure_steps_completed', models.IntegerField(default=0, help_text='Number of steps completed before failure')),
                ('failure_last_section', models.CharField(blank=True, help_text='Last form section accessed before giving up', max_length=100, null=True)),
                ('failure_abort_reason', models.TextField(blank=True, help_text='Reason for abandoning the form', null=True)),
                ('failure_notes', models.TextField(blank=True, help_text='Additional notes about the failure', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('form_output', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_groups', to='usability.formoutput')),
            ],
        ),
    ]
