# Generated by Django 5.2.5 on 2025-10-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='partial_abandon_reason',
            field=models.TextField(blank=True, help_text='Reason for partial completion', null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='partial_fields_completed',
            field=models.IntegerField(default=0, help_text='Number of fields completed in partial submission'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='partial_last_field',
            field=models.CharField(blank=True, help_text='Last field completed before stopping', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='partial_notes',
            field=models.TextField(blank=True, help_text='Additional notes about partial completion', null=True),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='outcome',
            field=models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failure', 'Failure')], max_length=10),
        ),
    ]
