# Generated by Django 5.2.5 on 2025-10-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usability', '0002_add_partial_completion_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formoutput',
            name='fields_required',
        ),
        migrations.AddField(
            model_name='formoutput',
            name='total_steps',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='formoutput',
            name='steps_planned',
            field=models.IntegerField(default=7),
        ),
    ]
